# Site settings
baseURL = "https://example.org/"
languageCode = "en-US"
title = "Anirudh Oppiliappan"
theme = "hugo-split-theme"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Metadata for search engines and social sharing
  name = "Anirudh Oppiliappan"
  description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
  shareImage = "images/social.jpg"
  twitterHandle = "icyphox"

  # Favicon
  favicon = "favicon.ico"

  # Copyright
  copyright = "&copy;2018 Anirudh Oppiliappan"

  # Section - Content
  [params.content]
    name = "Anirudh Oppiliappan"
    tagline = "Linux. Infosec. Open Source."
	bio = "Indpendent security researcher, frontend and backend web developer. I love Linux, free software and minimalism. Currently pursuing a CS undergrad." 

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "https://ik.imagekit.io/icyphox/background_rJjHnDicG.jpg"
      position = "bottom left"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Personal"

      [[params.links.list1.link]]
        text = "Blog"
        url = "https://ph0x.me/blog"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:icyph0x@pm.me"

      [[params.links.list1.link]]
        text = "Résumé"
        url = "https://xix.ph0x.me/resume.pdf"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Network"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/icyphox"

      [[params.links.list2.link]]
        text = "Keybase"
        url = "https://keybase.io/icyphox"

      [[params.links.list2.link]]
        text = "LinkedIn"
        url = "https://linkedin.com/in/icyphox"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Projects"
 
      [[params.links.list3.link]]
        text = "GitHub"
        url = "https://github.com/icyphox"
# 
#      [[params.links.list3.link]]
#        text = "Link Two"
#        url = "#"
# 
#      [[params.links.list3.link]]
#        text = "Link Three"
#        url = "#"
# 
  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
